#!/bin/bash

#功能：启动指定端口的tomcat-dsp
#用法：tomcatstart 7400 #7400为端口号
#2016-6-22 Joe.P

port=$1
#这里只能使用双引号或者不使用引号，但是不能使用单引号，会使shell变量和转义字符失效
path="/data/tomcat-*-${port}"
exe=${path}/bin/startup.sh
pid=`netstat -nlpt 2>/dev/null | grep -e ":${port} " --color | awk '{print $7}' | awk -F '/' '{print $1}' `
if [ -n "$pid" ]; then
	echo "tomcat已经启动了，无需重复启动"
	exit
fi

if [ -e $exe ]; then
	$exe
else
	echo "不存在对应端口的tomcat"
fi

exit
