#!/bin/bash

#功能：用于杀死指定端口的进程
#用法：eg: stoptomcat 7900, 7900为监听的端口
# 2016-6-22 Joe.P

port=$1
echo "将要杀死监听端口为 $port 的tomcat进程..."

#通过监听端口搜索进程pid
#nestat会在stderr输出"（并非所有进程都能被检测到，所有非本用户的进程信息将不会显示，如果想看到所有信息，则必须切换到 root 用户）"
#重定向至黑洞
pid=`netstat -nlpt 2>/dev/null | grep -e ":${port} " --color | awk '{print $7}' | awk -F '/' '{print $1}' `

#判读指定进程不为空
if [ -n "$pid" ];then
	echo "tomcat进程 $pid 将被杀死"
	kill -SIGKILL $pid
	echo "已杀死"
else
	echo "不存在监听指定端口的进程"
fi

exit
